import '@/styles/global.scss'
import styles from '@/styles/layout.module.scss'
import {Fira_Code} from 'next/font/google'
import {Header} from "@/components/Core/Header";

const firaCode = Fira_Code({subsets: ['latin']})

export const metadata = {
  title: 'Yurii Basarada: Web Developer',
  description: 'Generated by create next app',
  generator: "Next.js",
  manifest: "/manifest.json",
  themeColor: [{ media: "(prefers-color-scheme: dark)", color: "#fff" }],
  authors: [
    { name: "Yurii Basarada" },
    {
      name: "Yurii Basarada",
      url: process.env.LINKEDIN
    },
  ],
  viewport:
    "minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
  icons: [
    { rel: "apple-touch-icon", url: "icon-128x128.png" },
    { rel: "icon", url: "icon-128x128.png" },
  ],
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html className={styles.layout} lang="en">
    <body className={firaCode.className}>
    <Header/>
    <main>
      {children}
    </main>
    </body>
    </html>
  )
}
